// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    {type: 'autogenerated', dirName: '.'},
    {type: 'link', label: 'Download', href: 'https://vrcfury.com/download'},
    {type: 'link', label: 'Support Discord', href: 'https://vrcfury.com/discord'}
  ],
};

module.exports = sidebars;
